import type { Metadata } from "next";
import { Outfit, Playfair_Display, Rokkitt as Ronzino } from "next/font/google"; 
import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import Navbar from "./Component/Navbar";
import Footer from "./Component/Footer";
import { Toaster } from "react-hot-toast";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  weight: ["400"],
});

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  weight: ["400"],
});

const ronzino = Ronzino({
  variable: "--font-ronzino",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "DesiMati - Fresh To Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${outfit.variable} ${playfair.variable} ${ronzino.variable}`}
    >
      <body>
        <Navbar />
        {children}
        <Footer />

        <Toaster
          position="top-right"
          reverseOrder={false}
          toastOptions={{
            duration: 2000,
            style: {
              marginTop: "60px",
              marginRight: "20px",
              padding: "16px 24px",
              color: "#fff",
              fontSize: "14px",
              borderRadius: "10px",
              boxShadow: "0 4px 12px rgba(0,0,0,0.1)",
              animation: "slideIn 0.4s ease",
            },
            success: {
              style: {
                background: "#26A65B",
              },
            },
            error: {
              style: {
                background: "#ef4444",
              },
            },
          }}
        />
      </body>
    </html>
  );
}
